id: P010777
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:24:04.081269
source_metadata:
  id: bdr:W1KG15036
  title: ཨུརྒ་བཀའ་འགྱུར་གྱི་དཀར་ཆག
  author: ''
  volumes:
    a77faf3bd08d43a2a8629902c8ba98ac:
      image_group_id: I1KG15049
      title: ''
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
